### ISSUE TITLE
As a user I need to see a profile page when I click on the logout button.

### ISSUE THREAD

**Issue by jfgrissom** [FinDeckDao/findeck.io#36]
The login/logout button should have more options to see a profile, login, logout, and it should be named by the name of the user or the literal value "profile".

**Comment by aleksandr-mor** [comment]
It can be a profile icon instead of "Logout"
<img width="143" alt="Screenshot 2024-08-25 at 12 27 05 AM" src="https://github.com/user-attachments/assets/96ee41f7-e1c6-4421-a734-d4382004666b">

**Comment by jfgrissom** [comment]
Working on this today.

**Comment by jfgrissom** [comment]
The core of this feature is completed.
Basic profile creation and updating is available (commit a03b07e0b887d5d83dbed4d1adbca3380d4572e2).
